site_name: NFDI4Energy Service Definition
plugins:
  - tags:
      tags_file: categories.md 
theme: 
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - navigation.indexes 
  palette:
  # Palette toggle for dark mode
  - scheme: slate
    primary: custom
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  # Palette toggle for light mode
  - scheme: default
    primary: custom
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  features:
    - toc.integrate
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo_nfdi4energy.png
  favicon: assets/logo_nfdi4energy.png

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3



extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/FlorianK13/ServiceCollection