site_name: NFDI4Energy Service Definition
plugins:
  - tags:
      tags_file: index.md 
theme: 
  name: material
  palette:
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode